// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhklkcgQ6Xs27vUpftaAObVu9ZTHwyYDM',
    appId: '1:903113298048:web:1141af6e6168d1a0d45665',
    messagingSenderId: '903113298048',
    projectId: 'favorite-movie-practice',
    authDomain: 'favorite-movie-practice.firebaseapp.com',
    storageBucket: 'favorite-movie-practice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN246H0fLKiQxuLQyYDCfaiXWK3_KBW1M',
    appId: '1:903113298048:android:6ad177c5afeef356d45665',
    messagingSenderId: '903113298048',
    projectId: 'favorite-movie-practice',
    storageBucket: 'favorite-movie-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4oVHetpx3X3HSreJqDKA3sP5VdTzNKr0',
    appId: '1:903113298048:ios:6f3da2ffd53d3361d45665',
    messagingSenderId: '903113298048',
    projectId: 'favorite-movie-practice',
    storageBucket: 'favorite-movie-practice.appspot.com',
    iosClientId: '903113298048-nn8dk5rau6laarihqn289ds5e4aoks2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4oVHetpx3X3HSreJqDKA3sP5VdTzNKr0',
    appId: '1:903113298048:ios:38ac455877686ec6d45665',
    messagingSenderId: '903113298048',
    projectId: 'favorite-movie-practice',
    storageBucket: 'favorite-movie-practice.appspot.com',
    iosClientId: '903113298048-0jfgpr4hd4a121q5gr3h19lbr95phvq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mile2.RunnerTests',
  );
}
